import React from 'react';
import type { StoreSettings } from '../../types';
import { LayoutDashboard, ShoppingBag, Calendar, UtensilsCrossed, Tags, MapPin, Ticket, Settings, ExternalLink, LogOut, Bell, Image as ImageIcon, Users, X, ChevronLeft } from 'lucide-react';
export type AdminTab = 'dashboard'|'orders'|'schedule'|'products'|'categories'|'banners'|'neighborhoods'|'coupons'|'customers'|'settings';
interface Props { currentTab:AdminTab; onSelectTab:(tab:AdminTab)=>void; pendingOrdersCount:number; settings:StoreSettings; onGoToStore:()=>void; onLogout:()=>void; soundEnabled:boolean; onToggleSound:()=>void; isOpenOnMobile?:boolean; onCloseMobile?:()=>void; isCollapsed?:boolean; onToggleCollapse?:()=>void; }
export const AdminSidebar:React.FC<Props>=({currentTab,onSelectTab,pendingOrdersCount,settings,onGoToStore,onLogout,soundEnabled,onToggleSound,isOpenOnMobile=false,onCloseMobile,isCollapsed=false,onToggleCollapse})=>{
 const groups=[{name:'OPERAÇÃO',items:[{id:'dashboard',label:'Visão geral',icon:LayoutDashboard},{id:'orders',label:'Pedidos',icon:ShoppingBag},{id:'schedule',label:'Agenda',icon:Calendar}]},{name:'LOJA E CARDÁPIO',items:[{id:'products',label:'Produtos',icon:UtensilsCrossed},{id:'categories',label:'Categorias',icon:Tags},{id:'banners',label:'Banners',icon:ImageIcon},{id:'neighborhoods',label:'Entrega e taxas',icon:MapPin},{id:'coupons',label:'Cupons',icon:Ticket}]},{name:'GESTÃO',items:[{id:'customers',label:'Clientes',icon:Users},{id:'settings',label:'Configurações',icon:Settings}]}];
 return <>{isOpenOnMobile&&<button className="admin-backdrop" onClick={onCloseMobile} aria-label="Fechar menu administrativo"/>}<aside className={`admin-sidebar${isOpenOnMobile?' admin-sidebar-mobile-open':''}${isCollapsed?' collapsed':''}`}>
  <div className="admin-brand"><img src={settings.logo_url||'/brand.svg'} onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src='/brand.svg';}} width={38} height={38} alt=""/><div><strong>{settings.business_name||'Alfa Salgados'}</strong><small>Gestão da loja</small></div><button onClick={()=>isOpenOnMobile?onCloseMobile?.():onToggleCollapse?.()} aria-label="Ocultar menu lateral">{isOpenOnMobile?<X size={17}/>:<ChevronLeft size={17}/>}</button></div>
  <nav aria-label="Administração">{groups.map(group=><div className="admin-menu-group" key={group.name}><span>{group.name}</span>{group.items.map(item=>{const Icon=item.icon,active=currentTab===item.id;return <button className={active?'active':''} aria-current={active?'page':undefined} key={item.id} onClick={()=>{onSelectTab(item.id as AdminTab);onCloseMobile?.();}}><Icon size={18}/><span>{item.label}</span>{item.id==='orders'&&pendingOrdersCount>0&&<b>{pendingOrdersCount}</b>}</button>;})}</div>)}</nav>
  <div className="admin-sidebar-footer"><button className="admin-sound" onClick={onToggleSound} aria-pressed={soundEnabled}><Bell size={16}/><span>Som dos pedidos</span><b>{soundEnabled?'Ativo':'Mudo'}</b></button><button onClick={onGoToStore}><ExternalLink size={16}/>Ver loja</button><button className="admin-logout" onClick={onLogout}><LogOut size={16}/>Sair do painel</button></div>
 </aside></>;
};
